version: "3.7"
services:
  robloxtracker:
    image: robloxtracker:latest
    build: ./
    restart: unless-stopped
    env_file: .env
    expose:
      - 8080/tcp
    networks:
      - roblox
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      - roblox

networks:
  roblox:

volumes:
  prometheus_data:
